### Anything added to crawler_user_config.yml will overwrite these settings

# Max concurrent threadpool workers - setting this too high may cause connections to be dropped
threads: 800

# Max tasks in queue - higher will minimize database IO at cost of increased memory usage
max_queue: 20000

# Minimum time between node visitations (minutes)
crawl_interval: 15

# Proportion of connections which are followed up with a getaddr call. (0.0-1.0)
# After initial seeding it isn't necessary for this to be very high to discover all new nodes
# When --seed parameter is passed this is ignored
getaddr_prop: 0.15

# How much the block height has to differ from the median to be marked inactive
inactive_threshold:
  default: 48
  testnet: 48

# Attempt to establish connection with IPv6 nodes
ipv6: True

# Attempt to establish connection with .onion nodes
onion: True

# Tor proxy is required to connect to .onion address
tor_proxy: 127.0.0.1:9050

# order with which to process the networks
crawl_order:
  - testnet
  - groestlcoin

# Locks database table and updates Last_Checked BEFORE crawling nodes
# Performance overhead, but necessary if multiple processes are crawling concurrently using the same database
database_concurrency: True

# Socket timeout (seconds)
socket_timeout: 20

# Retries
retries: 1

# Retry only nodes seen in past X hours
retry_threshold: 48

# Used during connection handshake
user_agent: /groestl-nodes:0.1/
source_address: 0.0.0.0

# How many days to continue checking a node that has not yet been seen
min_pruning_age: 2

# How many days to continue checking a node that has previously been seen
max_pruning_age: 0

# If a seen node has been pruned from the database due to max_pruning_age, remove its visitation history as well
prune_visitations: False

# Active nodes are defined as nodes within +/- [inactive_threshold] of the median block height.
# If false inactive nodes will not be reported in the dumped files
export_inactive_nodes: False

# Excluded user agents - regex (see https://docs.python.org/3/library/re.html)
excluded_user_agents:
  - /BitCoinJ*

# historical data reporting interval (hours)
historic_interval: 4

# Protocol info for crawled networks
networks:
  groestlcoin:
    services: 0
    magic_number: f9beb4d4
    port: 1331
    protocol_version: 70002
    min_protocol_version: 70002
    dns_seeds:
      - dnsseed1.groestlcoin.org
      - dnsseed2.groestlcoin.org
      - dnsseed3.groestlcoin.org
      - dnsseed4.groestlcoin.org
    address_seeds:
      - 6brsrbiinpc32tfc.onion
      - xkj42efxrcy6vbfw.onion
      - j2pokkxrnqifawlo.onion
      - fxqag2xgbttgpn5t.onion
      - wbu6iwai7g5vsmqf.onion
      - ozarkd36gllcq64p.onion
      - lgafnxxckcohp3lb.onion
      - daxevrnxtrjtatnq.onion
      - 54fufvlyfsv6mu27.onion
      - oopkp4mazgysotus.onion
      - imfxdu2iaxphpzoj.onion
      - msu62n2wehlyvu73.onion
      - 4g54umgydy2efvkp.onion
      - nxb5shpaqcppuaac.onion
      - liciqskhe3kb56sx.onion
      - 6urwohx677tqyx4d.onion
      - jmkqrcrthxzgijzc.onion
      - o2i7q65crpvgkyhp.onion
      - sakl2ebpspx4yqux.onion
      - kahwte3yfwedilib.onion
      - 4jnj4nztibl6nzr7.onion
      - 7bh7oexd6sgaa2ui.onion
      - 6txnygqn2lo3pas7.onion
      - vhaltx6l3qz7m6gm.onion
      - pcorvh3z6l4qsfvh.onion
      - 4vncucq2hxqgobn4.onion
      - ezwaifwooob3xitg.onion
      - uqxfaectrpqqvogm.onion
      - tewjvvb2acejbpwu.onion
      - bmbrjepkos5brm3m.onion
      - evkxwqlvatx2bbuk.onion
      - ekjgl6n6jhcqfq2x.onion
      - 5seia6dn4dphcw4n.onion
      - c7kmgs5kd4wvgyo2.onion
      - ygovc7jlb6itiis4.onion
      - f33ys4h3e4nbdrdm.onion
      - csg7djvlqujxn4qt.onion
      - yw7dotigvofzqmql.onion
      - aal7howc56u3j5bg.onion
      - gnuvqomyhedouwqw.onion
  testnet:
    services: 0
    magic_number: 0b110907
    port: 17777
    protocol_version: 70002
    min_protocol_version: 70002
    dns_seeds:
    - testnet-seed1.groestlcoin.org
    - testnet-seed2.groestlcoin.org
    address_seeds:
    - aocojvqcybdoxekv.onion
    - 7frvhgofuf522b5i.onion

exclude_ipv4_networks:
  - 0.0.0.0/8
  - 10.0.0.0/8
  - 100.64.0.0/10
  - 127.0.0.0/8
  - 169.254.0.0/16
  - 172.16.0.0/12
  - 192.0.0.0/24
  - 192.0.0.0/29
  - 192.0.0.170/32
  - 192.0.0.171/32
  - 192.0.0.8/32
  - 192.0.2.0/24
  - 192.168.0.0/16
  - 192.175.48.0/24
  - 192.31.196.0/24
  - 192.52.193.0/24
  - 192.88.99.0/24
  - 198.18.0.0/15
  - 198.51.100.0/24
  - 203.0.113.0/24
  - 240.0.0.0/4
  - 255.255.255.255/32

# Set to 1 to receive all txs (unused)
relay: 0

# List of excluded ASNs
exclude_asns: []

# List of excluded IPv6 networks
exclude_ipv6_networks: []

# Bogons are addresses outside the range of valid ipv4 addresses
exclude_ipv4_bogons: True

# Use median percentile +/- N interquartile ranges in place of block height to determine activity
inactive_use_iqr: False
